image: node:14

before_script:
  - apt-get update -qq && apt-get install
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir .pnpm-store
  - pnpm prune

cache:
  key: "$CI_COMMIE_REF_SLUG"
  paths:
    - .pnpm-store

stages:
  - build
  - publish-docs

build-package:
  stage: build
  before_script:
    - rm -rf .yarn
    - pnpm install --frozen-lockfile
  script:
    - pnpm build

test-package:
  stage: build
  before_script:
    - rm -rf .yarn
    - pnpm install --frozen-lockfile
  script:
    - pnpm test:coverage
  artifacts:
    name: coverage
    paths:
      - coverage/
    expire_in: 30 days

pages:
  stage: publish-docs
  before_script:
    - rm -rf .yarn
    - pnpm install --frozen-lockfile
  script:
    - pnpm publish:docs
  artifacts:
    paths:
      - public
  only:
    - master

